minio:
  auth:
    rootUser: "admin"
    rootPassword: "password"
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: minio.lakehouse.local
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  defaultBuckets: "lakehouse, airflow, risingwave, kafka"
  persistence:
    enabled: true
    size: 20Gi
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2"
  env:
    - name: MINIO_API_REQUESTS_MAX
      value: "0"
    - name: MINIO_BROWSER_REQUESTS_MAX
      value: "0"
    - name: MINIO_BROWSER_UPLOAD_PART_SIZE
      value: "500MB"
